### ISSUE TITLE
Bechdel Test

### ISSUE THREAD

**Issue by elenado01** [serinachang5/bechdel#1]
Hi, 
i'm a data science student and i'm on my final year. I want to do my thesis on the Bechdel Test. Could you facilitate me some e-mail or something to contact you to ask you a few questions regarding your work on the Bechdel Test? 
Thank you very much,
Elena

**Comment by serinachang5** [comment]
Hi Elena,

Thanks for reaching out! You can reach me at serinac@stanford.edu.

Serina
